services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: reserva_backend
    volumes:
      - ./apps/backend:/var/www
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: reserva_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    working_dir: /app
    command: pnpm run dev --host
